# MYSQL_DB_NAME = "my_cart_app_db"
# MYSQL_USER = "<DB_USERNAME>"
# MYSQL_PASSWORD = "<DB_PASSWORD>"
# MYSQL_HOST = "<DB_HOST>"
# MYSQL_PORT = "<DB_PORT>"
#
# MAX_AMT_TO_DISCOUNT = 10000.00
# DISCOUNT_AMT = 500.00

MYSQL_DB_NAME = "my_cart_app_db"
MYSQL_USER = "hemant"
MYSQL_PASSWORD = "Hemant@123"
MYSQL_HOST = "localhost"
MYSQL_PORT = "3306"

MAX_AMT_TO_DISCOUNT = 10000.00
DISCOUNT_AMT = 500.00


TEST_MYSQL_DB_NAME = "test_my_cart_app_db"
TEST_MYSQL_USER = "hemant"
TEST_MYSQL_PASSWORD = "Hemant@123"
TEST_MYSQL_HOST = "localhost"
TEST_MYSQL_PORT = "3306"